[package]
name = "incremental_draw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anchors = "0.6.0"
leptos = { version = "0.4.2", features = ["csr"] }
